version: "3"
services:
    app:
        image: php:8-fpm
        volumes:
            - .:/var/www/html
            - ./app/php.ini:/usr/local/etc/php/php.ini
        build:
            context: ./
            dockerfile: Dockerfile
    web:
        image: nginx:latest
        depends_on:
            - app
        ports:
            - "8080:80"
        volumes:
            - ./web/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
    db:
        build: ./db
        volumes:
            - db-store:/var/lib/mysql
volumes:
    db-store: